//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpSite.Web.Locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharpSite.Web.Locales.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About SharpSite.
        /// </summary>
        internal static string sharpsite_about {
            get {
                return ResourceManager.GetString("sharpsite_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharpSite is a simple blog engine written in C# using Blazor..
        /// </summary>
        internal static string sharpsite_about_description {
            get {
                return ResourceManager.GetString("sharpsite_about_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packages Used.
        /// </summary>
        internal static string sharpsite_about_packages {
            get {
                return ResourceManager.GetString("sharpsite_about_packages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        internal static string sharpsite_accept {
            get {
                return ResourceManager.GetString("sharpsite_accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Plugin.
        /// </summary>
        internal static string sharpsite_addnewplugin {
            get {
                return ResourceManager.GetString("sharpsite_addnewplugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site admin.
        /// </summary>
        internal static string sharpsite_admin {
            get {
                return ResourceManager.GetString("sharpsite_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the SharpSite Admin Panel.
        /// </summary>
        internal static string sharpsite_admin_headertext {
            get {
                return ResourceManager.GetString("sharpsite_admin_headertext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage SharpSite.
        /// </summary>
        internal static string sharpsite_admin_layout_h1 {
            get {
                return ResourceManager.GetString("sharpsite_admin_layout_h1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Management.
        /// </summary>
        internal static string sharpsite_admin_layout_h2 {
            get {
                return ResourceManager.GetString("sharpsite_admin_layout_h2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to home.
        /// </summary>
        internal static string sharpsite_backtohome {
            get {
                return ResourceManager.GetString("sharpsite_backtohome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string sharpsite_delete {
            get {
                return ResourceManager.GetString("sharpsite_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string sharpsite_edit {
            get {
                return ResourceManager.GetString("sharpsite_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Page.
        /// </summary>
        internal static string sharpsite_editpage {
            get {
                return ResourceManager.GetString("sharpsite_editpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Post.
        /// </summary>
        internal static string sharpsite_editpost {
            get {
                return ResourceManager.GetString("sharpsite_editpost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        internal static string sharpsite_editpost_content {
            get {
                return ResourceManager.GetString("sharpsite_editpost_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string sharpsite_editpost_description {
            get {
                return ResourceManager.GetString("sharpsite_editpost_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish Date.
        /// </summary>
        internal static string sharpsite_editpost_publishdate {
            get {
                return ResourceManager.GetString("sharpsite_editpost_publishdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string sharpsite_editpost_title {
            get {
                return ResourceManager.GetString("sharpsite_editpost_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string sharpsite_generaladmin {
            get {
                return ResourceManager.GetString("sharpsite_generaladmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string sharpsite_home {
            get {
                return ResourceManager.GetString("sharpsite_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharpSite Home Page.
        /// </summary>
        internal static string sharpsite_home_page {
            get {
                return ResourceManager.GetString("sharpsite_home_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed plugins.
        /// </summary>
        internal static string sharpsite_installedplugins {
            get {
                return ResourceManager.GetString("sharpsite_installedplugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string sharpsite_loading {
            get {
                return ResourceManager.GetString("sharpsite_loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string sharpsite_login {
            get {
                return ResourceManager.GetString("sharpsite_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharpsite logo.
        /// </summary>
        internal static string sharpsite_logo {
            get {
                return ResourceManager.GetString("sharpsite_logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string sharpsite_logout {
            get {
                return ResourceManager.GetString("sharpsite_logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum upload size:.
        /// </summary>
        internal static string sharpsite_maxupload_label {
            get {
                return ResourceManager.GetString("sharpsite_maxupload_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin navigation.
        /// </summary>
        internal static string sharpsite_navadmin {
            get {
                return ResourceManager.GetString("sharpsite_navadmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main navigation.
        /// </summary>
        internal static string sharpsite_navmain {
            get {
                return ResourceManager.GetString("sharpsite_navmain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation menu.
        /// </summary>
        internal static string sharpsite_navmenu {
            get {
                return ResourceManager.GetString("sharpsite_navmenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Page.
        /// </summary>
        internal static string sharpsite_newpage {
            get {
                return ResourceManager.GetString("sharpsite_newpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Post.
        /// </summary>
        internal static string sharpsite_newpost {
            get {
                return ResourceManager.GetString("sharpsite_newpost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No plugins installed.
        /// </summary>
        internal static string sharpsite_nopluginsinstalled {
            get {
                return ResourceManager.GetString("sharpsite_nopluginsinstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Admin.
        /// </summary>
        internal static string sharpsite_pageadmin {
            get {
                return ResourceManager.GetString("sharpsite_pageadmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post not found.
        /// </summary>
        internal static string sharpsite_pagenotfound {
            get {
                return ResourceManager.GetString("sharpsite_pagenotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a Plugin to SharpSite.
        /// </summary>
        internal static string sharpsite_plugin_add {
            get {
                return ResourceManager.GetString("sharpsite_plugin_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin Author.
        /// </summary>
        internal static string sharpsite_plugin_author {
            get {
                return ResourceManager.GetString("sharpsite_plugin_author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin Description.
        /// </summary>
        internal static string sharpsite_plugin_description {
            get {
                return ResourceManager.GetString("sharpsite_plugin_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin File.
        /// </summary>
        internal static string sharpsite_plugin_file {
            get {
                return ResourceManager.GetString("sharpsite_plugin_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon of the plugin.
        /// </summary>
        internal static string sharpsite_plugin_icon {
            get {
                return ResourceManager.GetString("sharpsite_plugin_icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin Id.
        /// </summary>
        internal static string sharpsite_plugin_id {
            get {
                return ResourceManager.GetString("sharpsite_plugin_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin Name.
        /// </summary>
        internal static string sharpsite_plugin_name {
            get {
                return ResourceManager.GetString("sharpsite_plugin_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin Version.
        /// </summary>
        internal static string sharpsite_plugin_version {
            get {
                return ResourceManager.GetString("sharpsite_plugin_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin Website.
        /// </summary>
        internal static string sharpsite_plugin_website {
            get {
                return ResourceManager.GetString("sharpsite_plugin_website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin management.
        /// </summary>
        internal static string sharpsite_pluginmanagement {
            get {
                return ResourceManager.GetString("sharpsite_pluginmanagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published Date.
        /// </summary>
        internal static string sharpsite_postlist_publisheddate {
            get {
                return ResourceManager.GetString("sharpsite_postlist_publisheddate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string sharpsite_postlist_title {
            get {
                return ResourceManager.GetString("sharpsite_postlist_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posts Admin.
        /// </summary>
        internal static string sharpsite_postsadmin {
            get {
                return ResourceManager.GetString("sharpsite_postsadmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        internal static string sharpsite_reject {
            get {
                return ResourceManager.GetString("sharpsite_reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string sharpsite_remove {
            get {
                return ResourceManager.GetString("sharpsite_remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string sharpsite_save {
            get {
                return ResourceManager.GetString("sharpsite_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site appearance.
        /// </summary>
        internal static string sharpsite_site_appearance_admin {
            get {
                return ResourceManager.GetString("sharpsite_site_appearance_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Settings.
        /// </summary>
        internal static string sharpsite_sitesettings {
            get {
                return ResourceManager.GetString("sharpsite_sitesettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a theme.
        /// </summary>
        internal static string sharpsite_theme_blank_option {
            get {
                return ResourceManager.GetString("sharpsite_theme_blank_option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme selector.
        /// </summary>
        internal static string sharpsite_theme_selector {
            get {
                return ResourceManager.GetString("sharpsite_theme_selector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled error has occurred..
        /// </summary>
        internal static string sharpsite_unhandled_exception {
            get {
                return ResourceManager.GetString("sharpsite_unhandled_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string sharpsite_update {
            get {
                return ResourceManager.GetString("sharpsite_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Admin.
        /// </summary>
        internal static string sharpsite_useradmin {
            get {
                return ResourceManager.GetString("sharpsite_useradmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User list.
        /// </summary>
        internal static string sharpsite_userlist {
            get {
                return ResourceManager.GetString("sharpsite_userlist", resourceCulture);
            }
        }
    }
}
