<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore" />

		<PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\SharpSite.Abstractions.DataStorage\SharpSite.Abstractions.DataStorage.csproj" />
		<ProjectReference Include="..\..\src\SharpSite.Abstractions\SharpSite.Abstractions.csproj" />
	</ItemGroup>

</Project>
